### ISSUE TITLE
Bad `info` when adding a package to new project.

### ISSUE THREAD

**Issue by pinheadmz** [braydonf/gpk#14]
Attempting to use gpk to init a new project and add a dependency to it:

```
$ mkdir testp
$ cd testp/
$ gpk init
$ gpk install https://github.com/pinheadmz/monthly-balance#master
gpk: [info] Adding 'null' to package.
gpk: [info] Installing 'testp' at '/Users/matthewzipkin/Desktop/work/testp'.
gpk: [info] Copying 'null' at '59d462d40ab305765dc5ff109cbfe296aea487c0' to '/Users/matthewzipkin/Desktop/work/testp/node_modules/null'.
gpk: [error] TypeError: Cannot read property 'files' of null
    at Package.copyPackage (/Users/matthewzipkin/Desktop/work/gpk/lib/package.js:1277:40)
    at Package.installModule (/Users/matthewzipkin/Desktop/work/gpk/lib/package.js:655:15)
    at async Package.installDependencies (/Users/matthewzipkin/Desktop/work/gpk/lib/package.js:964:19)
    at async Package.install (/Users/matthewzipkin/Desktop/work/gpk/lib/package.js:753:7)
    at async /Users/matthewzipkin/Desktop/work/gpk/bin/gpk:118:16
```

The resulting `package.json` looks like its missing a little something:
```
$ cat package.json 
{
  "name": "testp",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "null": "git+https://github.com/pinheadmz/monthly-balance#master"
  }
}
```

The package in question [does have a name](https://github.com/pinheadmz/monthly-balance/blob/390ac1739b18c24ce2c622c01b8cee1870a5ab41/package.json#L2) but I think the `info` property of the `package` object during installation isn't getting referenced correctly. That would explain both errors (the missing name, and the missing files).

**Comment by braydonf** [comment]
Okay, looks like there are zero tags for that repo, and that case is not handled well.

**Comment by braydonf** [comment]
Closed in https://github.com/braydonf/gpk/commit/609c64a1357fe2ae7f966f3e9e51b86d0fa130a8
